# Generated by Django 4.2.20 on 2025-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('last_duty_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего наряда')),
                ('workload', models.FloatField(default=0.0, verbose_name='Нагрузка')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit.faculty', verbose_name='Факультет')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rank.rank', verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['full_name'],
            },
        ),
    ]
