# Generated by Django 4.2.20 on 2025-04-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDutyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_permitted_persons', to='duty.duty', verbose_name='Наряд')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_duty_permissions', to='people.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Допуск к наряду (факультет)',
                'verbose_name_plural': 'Допуски к нарядам (факультет)',
                'unique_together': {('person', 'duty')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentDutyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permitted_persons', to='duty.duty', verbose_name='Наряд')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_duty_permissions', to='people.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Допуск к наряду (кафедра)',
                'verbose_name_plural': 'Допуски к нарядам (кафедра)',
                'unique_together': {('person', 'duty')},
            },
        ),
    ]
