# Generated by Django 4.2.20 on 2025-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_name', models.CharField(max_length=50, verbose_name='Название наряда')),
                ('duty_weight', models.FloatField(verbose_name='Вес наряда')),
                ('is_commandant', models.BooleanField(default=False, verbose_name='Добавлено комендантом')),
                ('people_count', models.PositiveIntegerField(default=1, verbose_name='Количество людей')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties_as_department', to='unit.department', verbose_name='Закреплённая кафедра')),
                ('assigned_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties_as_faculty', to='unit.faculty', verbose_name='Закреплённый факультет')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='unit.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='unit.faculty', verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDutyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц планирования')),
                ('is_generated', models.BooleanField(default=False, verbose_name='График сгенерирован')),
                ('duty_schedule_settings', models.JSONField(blank=True, default=dict, help_text='JSON с настройками дней для каждого наряда', verbose_name='Настройки расписания нарядов')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Месячный план нарядов',
                'verbose_name_plural': 'Месячные планы нарядов',
            },
        ),
        migrations.CreateModel(
            name='MonthlyDutyPlanDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.duty')),
                ('monthly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.monthlydutyplan')),
            ],
            options={
                'db_table': 'duty_monthlydutyplan_duties',
                'unique_together': {('monthly_plan', 'duty')},
            },
        ),
        migrations.AddField(
            model_name='monthlydutyplan',
            name='duties',
            field=models.ManyToManyField(related_name='monthly_plans', through='duty.MonthlyDutyPlanDuty', to='duty.duty', verbose_name='Наряды в плане'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlydutyplan',
            unique_together={('month',)},
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата наряда')),
                ('time_start', models.TimeField(blank=True, help_text='Если не указано, считается на весь день', null=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, help_text='Если не указано, считается на весь день', null=True, verbose_name='Время окончания')),
                ('assigned_unit_type', models.CharField(blank=True, choices=[('faculty', 'Факультет'), ('department', 'Кафедра')], max_length=20, null=True, verbose_name='Тип подразделения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duty_schedules', to='unit.department', verbose_name='Назначенная кафедра')),
                ('assigned_faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duty_schedules', to='unit.faculty', verbose_name='Назначенный факультет')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='duty.duty', verbose_name='Наряд')),
            ],
            options={
                'verbose_name': 'План наряда',
                'verbose_name_plural': 'Планы нарядов',
                'ordering': ['date'],
                'unique_together': {('duty', 'date')},
            },
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_commandant', True)), fields=('duty_name',), name='unique_duty_for_commandant'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('faculty__isnull', False), ('is_commandant', False)), fields=('duty_name', 'faculty'), name='unique_duty_for_faculty'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('duty_name', 'department'), name='unique_duty_for_department'),
        ),
    ]
