# Generated by Django 4.2.20 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_name', models.CharField(max_length=50, unique=True, verbose_name='Название наряда')),
                ('duty_weight', models.FloatField(verbose_name='Вес наряда')),
            ],
            options={
                'verbose_name': 'Наряд',
                'verbose_name_plural': 'Наряды',
                'ordering': ['duty_name'],
            },
        ),
    ]
