# Generated by Django 4.2.20 on 2025-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name': 'Наряд', 'verbose_name_plural': 'Наряды'},
        ),
        migrations.AlterModelOptions(
            name='dutyschedule',
            options={'ordering': ['date', 'time_start'], 'verbose_name': 'План наряда', 'verbose_name_plural': 'Планы нарядов'},
        ),
        migrations.AlterModelOptions(
            name='monthlydutyplanduty',
            options={'verbose_name': 'Наряд в плане', 'verbose_name_plural': 'Наряды в планах'},
        ),
        migrations.AlterUniqueTogether(
            name='dutyschedule',
            unique_together={('duty', 'date', 'time_start', 'time_end')},
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='is_manually_assigned',
            field=models.BooleanField(default=False, verbose_name='Назначено вручную'),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
