# Generated by Django 4.2.20 on 2025-05-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={},
        ),
        migrations.AddField(
            model_name='duty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='unit.department', verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='duty',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duties', to='unit.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='duty',
            name='is_commandant',
            field=models.BooleanField(default=False, verbose_name='Добавлено комендантом'),
        ),
    ]
