# Generated by Django 4.2.20 on 2025-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_alter_duty_options_duty_department_duty_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='duty_name',
            field=models.CharField(max_length=50, verbose_name='Название наряда'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_commandant', True)), fields=('duty_name',), name='unique_duty_for_commandant'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('faculty__isnull', False), ('is_commandant', False)), fields=('duty_name', 'faculty'), name='unique_duty_for_faculty'),
        ),
        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('duty_name', 'department'), name='unique_duty_for_department'),
        ),
    ]
