# Generated by Django 4.2.20 on 2025-11-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_alter_duty_options_alter_dutyschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydutyplan',
            name='selected_units',
            field=models.JSONField(blank=True, default=list, help_text='JSON список выбранных подразделений для распределения', verbose_name='Выбранные подразделения'),
        ),
    ]
