# Generated by Django 4.2.20 on 2025-06-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('duty', '0003_alter_duty_duty_name_duty_unique_duty_for_commandant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties_as_department', to='unit.department', verbose_name='Закреплённая кафедра'),
        ),
        migrations.AddField(
            model_name='duty',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_duties_as_faculty', to='unit.faculty', verbose_name='Закреплённый факультет'),
        ),
        migrations.AddField(
            model_name='duty',
            name='people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество людей'),
        ),
    ]
