# Generated by Django 4.2.20 on 2026-02-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц планирования')),
                ('selected_units', models.JSONField(blank=True, default=list, help_text='JSON список: ["management"] или ["department_1", "department_2"]', verbose_name='Выбранные подразделения')),
                ('duty_schedule_settings', models.JSONField(blank=True, default=dict, help_text='JSON с настройками дней для каждого наряда', verbose_name='Настройки расписания нарядов')),
                ('is_generated', models.BooleanField(default=False, verbose_name='План сгенерирован')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_plans', to='unit.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Факультетский план',
                'verbose_name_plural': 'Факультетские планы',
                'unique_together': {('faculty', 'month')},
            },
        ),
    ]
