# Generated by Django 4.2.20 on 2025-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.CharField(max_length=30, unique=True, verbose_name='Звание'),
        ),
    ]
