# Generated by Django 4.2.20 on 2025-10-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата наряда')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='duty.duty', verbose_name='Наряд')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_records', to='people.people', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'duty'],
                'unique_together': {('duty', 'date', 'person')},
            },
        ),
    ]
