# Generated by Django 4.2.20 on 2026-01-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0003_monthlydutyplan_selected_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivenessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p_dc_v1_mean', models.FloatField(help_text='Средняя вероятность достижения цели для V1', verbose_name='P̄дц V1')),
                ('p_guaranteed_v1', models.FloatField(help_text='Гарантируемая вероятность для V1', verbose_name='Pₗ V1')),
                ('p_dc_v2_mean', models.FloatField(verbose_name='P̄дц V2')),
                ('p_guaranteed_v2', models.FloatField(verbose_name='Pₗ V2')),
                ('execution_time', models.FloatField(default=0, verbose_name='Время выполнения (сек)')),
                ('total_simulations', models.IntegerField(default=0, verbose_name='Всего симуляций')),
                ('raw_data_v1', models.JSONField(default=list, verbose_name='Данные V1')),
                ('raw_data_v2', models.JSONField(default=list, verbose_name='Данные V2')),
                ('conclusion', models.TextField(blank=True, verbose_name='Вывод')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='duty.monthlydutyplan')),
            ],
            options={
                'verbose_name': 'Отчёт эффективности',
                'verbose_name_plural': 'Отчёты эффективности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n1_scenarios', models.IntegerField(default=100, verbose_name='Число сценариев (N1)')),
                ('n2_runs', models.IntegerField(default=50, verbose_name='Число прогонов (N2)')),
                ('guarantee_level', models.FloatField(default=0.9, verbose_name='Уровень гарантии (L)')),
                ('z1', models.FloatField(default=0.9, verbose_name='ẑ₁ - мин. доля корректных')),
                ('z2', models.FloatField(default=0.8, verbose_name='ẑ₂ - мин. доля срочных')),
                ('z3', models.FloatField(default=0.1, verbose_name='ẑ₃ - макс. перегруз')),
                ('z4', models.FloatField(default=3.0, verbose_name='ẑ₄ - макс. перерасход')),
                ('z5', models.FloatField(default=2.0, verbose_name='ẑ₅ - макс. задержка')),
            ],
            options={
                'verbose_name': 'Сценарий исследования',
                'verbose_name_plural': 'Сценарии исследований',
            },
        ),
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('V1', 'V1'), ('V2', 'V2')], max_length=10, verbose_name='Вариант')),
                ('scenario_index', models.IntegerField(verbose_name='Номер сценария')),
                ('run_index', models.IntegerField(verbose_name='Номер прогона')),
                ('y1', models.FloatField(verbose_name='ŷ₁ - доля корректных')),
                ('y2', models.FloatField(verbose_name='ŷ₂ - срочные в срок')),
                ('y3', models.FloatField(verbose_name='ŷ₃ - перегруз')),
                ('y4', models.FloatField(verbose_name='ŷ₄ - перерасход')),
                ('y5', models.FloatField(verbose_name='ŷ₅ - макс. задержка')),
                ('is_success', models.BooleanField(verbose_name='Успех')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='research.effectivenessreport')),
            ],
            options={
                'verbose_name': 'Прогон СИМ',
                'verbose_name_plural': 'Прогоны СИМ',
                'ordering': ['scenario_index', 'run_index'],
            },
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchscenario'),
        ),
    ]
