# Generated by Django 4.2.20 on 2026-01-22 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0003_monthlydutyplan_selected_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название анализа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('analysis_results', models.JSONField(default=dict, verbose_name='Результаты сравнительного анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сравнительный анализ',
                'verbose_name_plural': 'Сравнительные анализы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duty_intensity_min', models.FloatField(default=5.0, help_text='Среднее число нарядов в день (мин)', verbose_name='Минимальная интенсивность нарядов')),
                ('duty_intensity_max', models.FloatField(default=15.0, help_text='Среднее число нарядов в день (макс)', verbose_name='Максимальная интенсивность нарядов')),
                ('urgency_ratio_min', models.FloatField(default=0.1, help_text='Минимальная доля срочных нарядов', verbose_name='Минимальная доля срочных')),
                ('urgency_ratio_max', models.FloatField(default=0.4, help_text='Максимальная доля срочных нарядов', verbose_name='Максимальная доля срочных')),
                ('availability_mean', models.FloatField(default=0.85, help_text='Средний коэффициент доступности', verbose_name='Средняя доступность подразделений')),
                ('availability_std', models.FloatField(default=0.1, help_text='Разброс коэффициента доступности', verbose_name='Стандартное отклонение доступности')),
                ('resource_constraints', models.JSONField(default=dict, help_text='JSON с ограничениями по ресурсам', verbose_name='Ограничения ресурсов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Набор параметров исследования',
                'verbose_name_plural': 'Наборы параметров исследований',
            },
        ),
        migrations.AlterModelOptions(
            name='researchscenario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сценарий исследования', 'verbose_name_plural': 'Сценарии исследований'},
        ),
        migrations.AlterModelOptions(
            name='simulationrun',
            options={'ordering': ['scenario_index', 'run_index', 'variant'], 'verbose_name': 'Прогон СИМ', 'verbose_name_plural': 'Прогоны СИМ'},
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ci_v1_lower',
            field=models.FloatField(default=0.0, verbose_name='ДИ V1 нижняя граница'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ci_v1_upper',
            field=models.FloatField(default=0.0, verbose_name='ДИ V1 верхняя граница'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ci_v2_lower',
            field=models.FloatField(default=0.0, verbose_name='ДИ V2 нижняя граница'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ci_v2_upper',
            field=models.FloatField(default=0.0, verbose_name='ДИ V2 верхняя граница'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='correlation_pearson',
            field=models.FloatField(default=0.0, help_text='r = cov(X,Y) / (σ_X·σ_Y)', verbose_name='Коэффициент корреляции Пирсона'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='correlation_spearman',
            field=models.FloatField(default=0.0, help_text='Коэффициент ранговой корреляции', verbose_name='Коэффициент корреляции Спирмена'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='cv_v1',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент вариации V1 (%)'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='cv_v2',
            field=models.FloatField(default=0.0, verbose_name='Коэффициент вариации V2 (%)'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='degrees_of_freedom',
            field=models.IntegerField(default=0, verbose_name='Степени свободы'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='graph_data',
            field=models.JSONField(default=dict, help_text='Данные для построения гистограмм, CDF, диаграмм рассеяния и радарных диаграмм', verbose_name='Данные для графиков'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ks_p_value',
            field=models.FloatField(default=1.0, verbose_name='KS p-значение'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='ks_statistic',
            field=models.FloatField(default=0.0, verbose_name='D-статистика Колмогорова-Смирнова'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='kurtosis_v1',
            field=models.FloatField(default=0.0, verbose_name='Эксцесс V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='kurtosis_v2',
            field=models.FloatField(default=0.0, verbose_name='Эксцесс V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='max_v1',
            field=models.FloatField(default=0.0, verbose_name='Максимальное значение V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='max_v2',
            field=models.FloatField(default=0.0, verbose_name='Максимальное значение V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='median_v1',
            field=models.FloatField(default=0.0, verbose_name='Медиана V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='median_v2',
            field=models.FloatField(default=0.0, verbose_name='Медиана V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='metrics_breakdown',
            field=models.JSONField(default=list, help_text='Детальный анализ вклада ŷ₁...ŷ₅ в P₄Ц', verbose_name='Анализ показателей качества'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='min_v1',
            field=models.FloatField(default=0.0, verbose_name='Минимальное значение V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='min_v2',
            field=models.FloatField(default=0.0, verbose_name='Минимальное значение V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='p_value',
            field=models.FloatField(default=1.0, help_text='Вероятность наблюдения результата при верной H₀', verbose_name='p-значение'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='r_squared',
            field=models.FloatField(default=0.0, help_text='Доля дисперсии Y, объяснённая X', verbose_name='Коэффициент детерминации R²'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='regression_intercept',
            field=models.FloatField(default=0.0, verbose_name='Свободный член регрессии (β₀)'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='regression_slope',
            field=models.FloatField(default=0.0, verbose_name='Наклон регрессии (β₁)'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='skewness_v1',
            field=models.FloatField(default=0.0, verbose_name='Асимметрия V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='skewness_v2',
            field=models.FloatField(default=0.0, verbose_name='Асимметрия V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='std_v1',
            field=models.FloatField(default=0.0, verbose_name='Стандартное отклонение V1'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='std_v2',
            field=models.FloatField(default=0.0, verbose_name='Стандартное отклонение V2'),
        ),
        migrations.AddField(
            model_name='effectivenessreport',
            name='t_statistic',
            field=models.FloatField(default=0.0, help_text='t = (ȳ₁ - ȳ₂) / (s_p·√(1/n₁ + 1/n₂))', verbose_name='t-статистика Стьюдента'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='calculation_time',
            field=models.FloatField(default=0.0, help_text='Время выполнения алгоритма распределения', verbose_name='Время расчёта (мс)'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата прогона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='memory_usage',
            field=models.FloatField(default=0.0, verbose_name='Использование памяти (МБ)'),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='success_reason',
            field=models.TextField(blank=True, verbose_name='Причина успеха/неудачи'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='p_dc_v1_mean',
            field=models.FloatField(default=0.0, help_text='Средняя вероятность достижения цели для V1', verbose_name='P̄дц V1'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='p_dc_v2_mean',
            field=models.FloatField(default=0.0, verbose_name='P̄дц V2'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='p_guaranteed_v1',
            field=models.FloatField(default=0.0, help_text='Гарантируемая вероятность для V1 при L=0.9', verbose_name='P₀.₉ V1'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='p_guaranteed_v2',
            field=models.FloatField(default=0.0, verbose_name='P₀.₉ V2'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_reports', to='duty.monthlydutyplan', verbose_name='План распределения'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='raw_data_v1',
            field=models.JSONField(default=list, help_text='Первые 20 оценок вероятности для V1', verbose_name='Сырые данные V1'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='raw_data_v2',
            field=models.JSONField(default=list, help_text='Первые 20 оценок вероятности для V2', verbose_name='Сырые данные V2'),
        ),
        migrations.AlterField(
            model_name='effectivenessreport',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchscenario', verbose_name='Сценарий исследования'),
        ),
        migrations.AlterField(
            model_name='researchscenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='researchscenario',
            name='n1_scenarios',
            field=models.IntegerField(default=100, verbose_name='Число сценариев (N₁)'),
        ),
        migrations.AlterField(
            model_name='researchscenario',
            name='n2_runs',
            field=models.IntegerField(default=50, verbose_name='Число прогонов (N₂)'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Цель достигнута'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='research.effectivenessreport', verbose_name='Отчёт'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='run_index',
            field=models.IntegerField(help_text='i = 1...N₂', verbose_name='Номер прогона внутреннего цикла'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='scenario_index',
            field=models.IntegerField(help_text='l = 1...N₁', verbose_name='Номер сценария внешнего цикла'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='variant',
            field=models.CharField(choices=[('V1', 'V1 - Агрегированная модель'), ('V2', 'V2 - Детализированная модель')], max_length=2, verbose_name='Вариант модели'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='y1',
            field=models.FloatField(default=0.0, verbose_name='ŷ₁ - доля корректных назначений'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='y2',
            field=models.FloatField(default=0.0, verbose_name='ŷ₂ - доля срочных нарядов в срок'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='y3',
            field=models.FloatField(default=0.0, verbose_name='ŷ₃ - показатель перегруза'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='y4',
            field=models.FloatField(default=0.0, verbose_name='ŷ₄ - перерасход ресурса'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='y5',
            field=models.FloatField(default=0.0, verbose_name='ŷ₅ - максимальная задержка'),
        ),
        migrations.AlterUniqueTogether(
            name='simulationrun',
            unique_together={('report', 'variant', 'scenario_index', 'run_index')},
        ),
        migrations.AddIndex(
            model_name='effectivenessreport',
            index=models.Index(fields=['created_at'], name='research_ef_created_637202_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivenessreport',
            index=models.Index(fields=['plan', 'scenario'], name='research_ef_plan_id_2d9e85_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['variant', 'is_success'], name='research_si_variant_43f612_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationrun',
            index=models.Index(fields=['scenario_index', 'run_index'], name='research_si_scenari_cb378d_idx'),
        ),
        migrations.AddField(
            model_name='comparativeanalysis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='comparativeanalysis',
            name='reports',
            field=models.ManyToManyField(related_name='comparative_analyses', to='research.effectivenessreport', verbose_name='Отчёты для сравнения'),
        ),
    ]
