# Generated by Django 4.2.20 on 2025-04-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.CharField(choices=[('illness', 'Болезнь'), ('business_trip', 'Командировка'), ('vacation', 'Отпуск'), ('other', 'Другое')], default='illness', max_length=50, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_missing', to='people.people', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Освобождение от факультета',
                'verbose_name_plural': 'Освобождения от факультетов',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMissing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.CharField(choices=[('illness', 'Болезнь'), ('business_trip', 'Командировка'), ('vacation', 'Отпуск'), ('other', 'Другое')], default='illness', max_length=50, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_missing', to='people.people', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Освобождение от кафедры',
                'verbose_name_plural': 'Освобождения от кафедр',
                'ordering': ['-start_date'],
            },
        ),
    ]
